version: "3"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"
    volumes:
      - .:/api
    depends_on:
      - postgres
      - pgadmin 

  postgres:
    container_name: postgres
    image: postgres:10    
    env_file: .env
    volumes:
       - postgres:/data/postgres
    ports:
       - 5432
  
  pgadmin:
    container_name: pgadmin
    logging:
      driver: none
    image: dpage/pgadmin4
    env_file: .env
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

volumes:
    postgres:
    pgadmin:
